### ISSUE TITLE
PackageManager.InstallPackage throw exception

### ISSUE THREAD

**Issue by raozhihao** [yungd1plomat/AdvancedSharpAdbClient#1]
.net :4.7.2
file version:1.3.0.0
nuget version:2.5.1

when i use InstallPackage,
always reporting an exception

AdvancedSharpAdbClient.Exceptions.AdbException:“missing , in ID_SEND_V1”

**code:**
` public string InstallApp(string appPath)
        {
            PackageManager manager = new PackageManager(this.client, device);
            
            manager.InstallPackage(appPath, reinstall: true);
            return "Success";
        }`

**Comment by raozhihao** [comment]
use AdvancedAdbClient.Install is ok

**Comment by yungd1plomat** [comment]
You need Root for PackageManager, because it's push apk into device and then install it. (only root has access to /data/local/tmp/... not sure how adb does it then...)
AdvancedAdbClient.Install uses stream to install package and it doesn't need Root.
