### ISSUE TITLE
Add split app support

### ISSUE THREAD

**Issue by wherewhere** [yungd1plomat/AdvancedSharpAdbClient#10]
Install split apps need `install-multiple` command. But I didn't find a way to execute this command. Using `ExecuteRemoteCommand` 
it say `/system/bin/sh: install-multiple: inaccessible or not found`. Could add support for Split APK?

**Comment by yungd1plomat** [comment]
> 

If you want to add more functionality, you can send pr

**Comment by wherewhere** [comment]
...

**Comment by wherewhere** [comment]
#14
