### ISSUE TITLE
Does it work with MAUI?

### ISSUE THREAD

**Issue by sharpordie** [yungd1plomat/AdvancedSharpAdbClient#17]
### Describe your question

I would like to know if the package works with MAUI for the Android and iOS platforms?

Thanks in advance. ;)

**Comment by wherewhere** [comment]
Android and iOS don't have adb server. Maybe you can connect to adb server in other device. But it is useless...

**Comment by sharpordie** [comment]
No Google official support doesn't mean it doesn't exist. ;)

Adb can be compiled for android and it's working perfectly.
https://github.com/nightmare-space/adb_tool/issues/4

The adb-ios project is old but it works totally fine for me.
https://github.com/zonghai-li/adb-ios/issues/11

**Comment by wherewhere** [comment]
Anyway, if you can start adb server on the default localhost port, it maybe functional. You can try by yourself.

**Comment by yungd1plomat** [comment]
No

**Comment by wherewhere** [comment]
> No

No, Yes.
![-bbcf97223b04c37.jpg](https://user-images.githubusercontent.com/27689196/172807391-abd8c5b1-551d-4b0b-b4c3-488cdadd35ed.jpg)

**Comment by mediaexplorer74** [comment]
> Anyway, if you can start adb server on the default localhost port, it maybe functional. You can try by yourself.

Very interesting. As I remember, Project Astoria (oldest Win10Preview) also uses adb.... ^ ^ 
Maybe one day some hacker will do remake of multi-platform APK->APPX convertor+installer :)

**Comment by wherewhere** [comment]
You need to build an arm32 ADB at first...

**Comment by mediaexplorer74** [comment]
> You need to build an arm32 ADB at first... 

Oh... Is AdvancedSharpAdbClient dependant from some adb.exe? So bad, too bad... 
adb is not .net soft :(

**Comment by GreenShadeZhang** [comment]
> Android and iOS don't have adb server. Maybe you can connect to adb server in other device. But it is useless...

Does it support mac m1 computer？

**Comment by wherewhere** [comment]
Need a M1 Mac to test.

**Comment by GreenShadeZhang** [comment]
> Need a M1 Mac to test.

I have a m2 Mac, if the code implementation level is compatible, I can use it to develop MAUI APP for testing.
