### ISSUE TITLE
System.ArgumentOutOfRangeException: ''

### ISSUE THREAD

**Issue by megapro17** [yungd1plomat/AdvancedSharpAdbClient#19]
### What can we do for you?

When I'm using GetDirectoryListing for the second time, it shows me an empty exception. What's wrong? 
![image](https://user-images.githubusercontent.com/16743370/170848513-048731de-4be1-4ca1-9031-7f3315cf1172.png)

**Comment by wherewhere** [comment]
Please use this [template](https://github.com/yungd1plomat/AdvancedSharpAdbClient/issues/new?template=bug_report.yaml) if you find a bug.
Or please tell us which version of nuget package and dotnet platform you used.

**Comment by megapro17** [comment]
is this a bug or i'm doing something wrong??

**Comment by wherewhere** [comment]
It's a bug. But I don't know how to fix it. You can renew the class and it will functional...

**Comment by wherewhere** [comment]
> try to call service.Open(), like this
> ```C#
> SyncService service = new SyncService(client, device);
> var a = service.GetDirectoryListing("/");
> service.Open();
> var b = service.GetDirectoryListing("/sdcard");
> ```

Sorry, it's not functional 🤣
