### ISSUE TITLE
Need help for Implicit and Explicit wait in AdvancedSharpAdbClient

### ISSUE THREAD

**Issue by nishikantkamble** [yungd1plomat/AdvancedSharpAdbClient#20]
### What can we do for you?

While working with AdvancedSharpAdbClient , for android element automation, sometimes few elements not loaded properly, or the elements configuration not matches, so there may be the any reason, so for that we want to wait for the element will appear or something like  wait.until(ExpectedConditions.visibilityOf(), so for that we want explicit wait. So I request if anything is already then it will be good or plz suggest the solution for this.
Advance Thanking you...

**Comment by wherewhere** [comment]
I think this is a feature request which need use this [template](https://github.com/yungd1plomat/AdvancedSharpAdbClient/issues/new?template=feature_request.yaml)......
(Why everyone use help-want template to create issues. 😂😂😂

**Comment by yungd1plomat** [comment]
Yes, this feature is already implemented, you can specify the waiting time with the third argument

`Element el = client.FindElement(device, "//node[@text='Login']", TimeSpan.FromSeconds(5));` - wait for element 5 second and return null if element not found
