### ISSUE TITLE
DumpScreen relies on Xml string not containing "ERROR" inside

### ISSUE THREAD

**Issue by Lyrapuff** [yungd1plomat/AdvancedSharpAdbClient#24]
### Describe the bug

If you call `DumpScreen(DeviceData device)` on `AdvancedAdbClient` it'll return null if the dumped Xml contains "ERROR" anywhere inside, even if it's just text in an element

### Steps to reproduce the bug

1. On device open anything that contains text "ERROR"
2. Call `DumpScreen`
3. It returns null

### Expected behavior

Get an XmlDocument

### NuGet package version

2.5.2

### .NET Platform

.NET 6

### Platform type

Windows

### System version

Windows 10

### IDE

Other

### Additional context

Does this check really have to be like this? Maybe it can be changed to Equals instead of Contains or even simply be removed

**Comment by wherewhere** [comment]
It return `null` because it has
```cs
if (xmlString != "" && !xmlString.Contains("ERROR"))
{
    doc.LoadXml(xmlString);
    return doc;
}
```
But I don't know what it real error return...

**Comment by wherewhere** [comment]
Got it. The error is `ERROR: could not get idle state.`.
