### ISSUE TITLE
Planned release?

### ISSUE THREAD

**Issue by ztamas83** [yungd1plomat/AdvancedSharpAdbClient#30]
Hi! Do you have a plan in mind for the next release? There are quite some changes after the latest release.

**Comment by ztamas83** [comment]
@yungd1plomat do you have any comment on this? I really would like to have an updated version into my application

**Comment by yungd1plomat** [comment]
Yeah, I'll release it one of these days.

**Comment by wherewhere** [comment]
New release published !
