### ISSUE TITLE
Issue when using "AdbClient.Connect" with WPF application

### ISSUE THREAD

**Issue by jerry-synap** [yungd1plomat/AdvancedSharpAdbClient#38]
### Describe your question

Hello,

If I use the following piece of code in a Winforms app, the call/process takes <10ms but the same code when used in a WPF application (bare bones app), the same call takes 2600ms. Any idea why that is?

```cs
var result = adbclient.Connect("192.168.1.111");
```

or even 

```cs
var result = adbclient.ConnectAsync("192.168.1.111");
```

**Comment by wherewhere** [comment]
Because it need this time. You can try to use adb directly, it need such time too.

**Comment by wherewhere** [comment]
If you don't want to wait, you can just don't await it.

**Comment by wherewhere** [comment]
In old version, the connect will not wait for the results. So it only send the command and return back noting. So it will not take long times.
