### ISSUE TITLE
Screenshot error report

### ISSUE THREAD

**Issue by changmiao007** [yungd1plomat/AdvancedSharpAdbClient#41]
### Describe the bug

```cs
static async void Main(string[] args)
{
    ...
    System.Drawing.Image img = client.GetFrameBufferAsync(device, CancellationToken.None).GetAwaiter().GetResult(); // synchronously
    ...
    System.Drawing.Image img = await client.GetFrameBufferAsync(device, CancellationToken.None); // asynchronously
    ...
}
```

**System.IO.EndOfStreamException    Cannot read outside the end of the stream**

### Steps to reproduce the bug

An error is reported when the screenshot function is called

### NuGet package version

2.5.4

### .NET Platform

.NET Framework 4.6.x

### Platform type

Windows

### IDE

Visual Studio 2017

**Comment by wherewhere** [comment]
#29
No more this kind issue...

**Comment by wbacsn** [comment]
I had the same problem, the system would get stuck there and never read the image data.

**Comment by ilamp** [comment]
This can be closed now @wherewhere
