### ISSUE TITLE
Default port doubling

### ISSUE THREAD

**Issue by RAREGUN** [yungd1plomat/AdvancedSharpAdbClient#53]
### Describe the bug

Somehow calling ConnectAsync overload without port doubles default port

### Steps to reproduce the bug

Calling `string result = await client.ConnectAsync("127.0.0.1", cancellationToken: token);`
will produce `unable to connect to 127.0.0.1:5555:5555`

### NuGet package version

2.5.5

### .NET Platform

.NET 7

### Platform type

Windows

**Comment by RAREGUN** [comment]
In fact, the port is not duplicated, this is a message output issue

**Comment by wherewhere** [comment]
???

**Comment by wherewhere** [comment]
Is that something wrong with your adb?
![image](https://github.com/yungd1plomat/AdvancedSharpAdbClient/assets/27689196/3bef92fa-34f1-4e64-a38b-4b0f4377e436)

**Comment by RAREGUN** [comment]
> Is that something wrong with your adb?

Exactly
