### ISSUE TITLE
ShellCommandUnresponsiveException while DumpScreenAsync

### ISSUE THREAD

**Issue by RAREGUN** [yungd1plomat/AdvancedSharpAdbClient#55]
### Describe the bug

Getting this exception only while this screen (Look screenshots section).
I think that the timer is to blame for everything, because when it expires, the exception stops appearing.
The worst part of all this is that after getting this exception at least once, it most likely breaks something and I get this exception regardless of whether I closed this page with a timer or not.

I'm using virtual machine with android 9.
App on screenshot: [Official Telegram mobile client](https://telegram.org/android?setln=en)

```
System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at AdvancedSharpAdbClient.AdbClient.DumpScreenAsync(DeviceData device, CancellationToken cancellationToken)
```

### Steps to reproduce the bug

Try to DumpScreenAsync while "Enter code" page.
This is very complicated to reproduce this bug by yourself, it's costs 0.34$ each time :)
But I'm all yours.

### Screenshots

![image](https://github.com/yungd1plomat/AdvancedSharpAdbClient/assets/46169975/7932271d-c49d-4d7a-b282-b916d9668f8c)

### NuGet package version

2.5.5

### .NET Platform

.NET 7

### Platform type

Windows

### System version

Windows 11 Pro 22H2 22621.1413

### IDE

Other

**Comment by RAREGUN** [comment]
I tried to inject logger to DumpScreenAsync like this:
![image](https://github.com/yungd1plomat/AdvancedSharpAdbClient/assets/46169975/1e65ce48-99c9-4380-a8a3-2d9a190d3743)
And logs i got:
![image](https://github.com/yungd1plomat/AdvancedSharpAdbClient/assets/46169975/56dd37ff-2c1d-4bcb-97af-07850cb54f03)
1) When we are trying to dump timer page first time.
2) Idk, page transition?
3) When timer page has gone and we are looking at dumpable page, but not now because of exception before

**Comment by wherewhere** [comment]
I can get xml in my device. Could you debug it with source?

**Comment by wherewhere** [comment]
I can only add judgment to `java.lang.Exception`
![image](https://github.com/yungd1plomat/AdvancedSharpAdbClient/assets/27689196/2d7b7dc7-2c96-433a-91ee-cd8fc0ec68c8)

**Comment by RAREGUN** [comment]
Sorry my mistake, `Polly.Policy.TimeoutAsync` didn't throw a `TimeoutRejectedException` when time ran out and the `while (!cancellationToken.IsCancellationRequested)` loop inside `FindElementsAsync` method kept spinning forever causing a brute force attack on the ADB server

**Comment by RAREGUN** [comment]
I made a mistake again. The issue is still present, but the error now is `ERROR: could not get idle state.`. It appears only when the timer is running. What does this error mean and how to avoid?

**Comment by wherewhere** [comment]
This is a error report by adb. You should ask to Google...

**Comment by phuongbk90** [comment]
> I made a mistake again. The issue is still present, but the error now is `ERROR: could not get idle state.`. It appears only when the timer is running. What does this error mean and how to avoid?

Hi, You should use below repo to dump screen.
https://github.com/dtmilano/CulebraTester2-public 

Default uiautomator by google is limitation and you can only dump static screen.
