### ISSUE TITLE
How to change default AdbServerPort(5037) ?

### ISSUE THREAD

**Issue by Andronovo-bit** [yungd1plomat/AdvancedSharpAdbClient#59]
### Describe your question

Hello;

I have an error in the like below image. In my computer, **adbserver** run on **5038** port.  How to i set this settings ?

![image](https://github.com/yungd1plomat/AdvancedSharpAdbClient/assets/24398592/9f9b5a23-d9c2-4b41-acb9-b5c8218ab897)

**Comment by Andronovo-bit** [comment]
I solved own problem :) 

It is a solution

![image](https://github.com/yungd1plomat/AdvancedSharpAdbClient/assets/24398592/5da82aab-1ec0-4bb8-9a2f-f208f2a72e3a)

**Comment by wherewhere** [comment]
<img alt="幽灵" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" /><img alt="幽灵" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" /><img alt="幽灵" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" />
