### ISSUE TITLE
FindElements return null

### ISSUE THREAD

**Issue by atimofeev86** [yungd1plomat/AdvancedSharpAdbClient#6]
Hey.
I use real phones.
In my case FindElement\FindElements alwways return null.
I tried:
client.FindElements(device, "//node[@class='android.widget.ImageView']");
client.FindElements(device, "//node");
client.FindElements(device, "//android.widget.ImageView");

**Comment by yungd1plomat** [comment]
use in lowercase, example client.FindElements(device, "//node[@class='android.widget.ImageView']");

There are all node attributes:
![image](https://user-images.githubusercontent.com/64736191/140726387-cd143e5e-62a3-4c0c-b81f-147e347b7c7e.png)

**Comment by atimofeev86** [comment]
![2021-11-08_13-37-17](https://user-images.githubusercontent.com/41478386/140735418-55be5c87-a929-4919-abfe-4f54c04f8c25.png)
Nothing

**Comment by yungd1plomat** [comment]
![image](https://user-images.githubusercontent.com/64736191/140736312-d02ea87b-4274-4083-a1d5-117a52b3c804.png)

not @Class, use @class

**Comment by atimofeev86** [comment]
![2021-11-08_16-54-17](https://user-images.githubusercontent.com/41478386/140764234-5f820f78-ea9e-4a90-ba1c-3b17df213d98.png)
I'm using lowercase

**Comment by yungd1plomat** [comment]
`var doc = client.DumpScreen(device);
doc.Save('test.xml');`
And send document here

**Comment by atimofeev86** [comment]
![2021-11-08_20-04-28](https://user-images.githubusercontent.com/41478386/140794497-5f63940e-df22-4417-8175-3bbfa2d37754.png)
it's null

**Comment by yungd1plomat** [comment]
> ![2021-11-08_20-04-28](https://user-images.githubusercontent.com/41478386/140794497-5f63940e-df22-4417-8175-3bbfa2d37754.png) it's null

Check if developer mode is enabled in your phone settings and if you have root
