### ISSUE TITLE
Is there a way of seeing if a FileStatisitcs result is a dir or file?

### ISSUE THREAD

**Issue by prosthetichead** [yungd1plomat/AdvancedSharpAdbClient#61]
I can't see an easy way of seeing this from the provided stats. Is there a way to see if a read statistics result is a file or directory?

I did have a idea of working it out by running everything through GetDirectoryListing and checking the result but wanted to check before I went down that path.

**Comment by wherewhere** [comment]
You can use `ls` command of Linux...

**Comment by prosthetichead** [comment]
Sorry how would I use the LS command of Linux when looking through the results returned by the GetDirectoryListing function?

**Comment by wherewhere** [comment]
The path end with `/` is directory...
![Screenshot_20230625-133111.jpg](https://github.com/yungd1plomat/AdvancedSharpAdbClient/assets/27689196/3cb3a1ea-0883-4a6c-aad9-fc3ed9a2901f)

**Comment by wherewhere** [comment]
I have considered to create a file manager through Linux command. But it is so weird and I give it up. Maybe you can reference it.
https://github.com/yungd1plomat/AdvancedSharpAdbClient/blob/feature/filemanagement/AdvancedSharpAdbClient/FileManager/AdbFileSystem.cs

**Comment by prosthetichead** [comment]
How do I use the FileManager classes and AdbFileSystem, this looks like exactly what I'm looking for. 

Some background of what I'm trying to use AdvancedSharpAdbClient for.  The handheld console RG35xx uses ADB and I'm trying to write a little tool to interact with the file system on the device without taking out the SD card. I got it all connecting but I need a little more feature with interacting with files from the c# code.

**Comment by prosthetichead** [comment]
Oh ok looking through it more I think I understand why you keep saying use the LS command. Do you mean use method ExecuteRemoteCommand to execute LS on the device?

**Comment by prosthetichead** [comment]
I whipped up a little console display to send raw execute commands to the device and so far so good. This has helped a lot thankyou. 
![image](https://github.com/yungd1plomat/AdvancedSharpAdbClient/assets/1934681/e90fe291-d3f3-4c96-9761-1b1c4cbcbdc8)

**Comment by wherewhere** [comment]
That's it.
