### ISSUE TITLE
adb devices

### ISSUE THREAD

**Issue by Slappyzz** [yungd1plomat/AdvancedSharpAdbClient#64]
### What can we do for you?

Dear yungd1plomat,

My name is SlappyZ, and I am an avid user of ADB (Android Debug Bridge). Lately, I've been attempting to execute the "adb devices" command on my system to retrieve a list of connected devices and emulators. 

I have been trying to check the Nox Player instances on my system, as I use multiple Nox instances for my development and testing purposes. The "adb devices" command should typically provide a list of connected devices and emulators along with their respective serial numbers, but instead, I'm not getting any response.

Here is some information about my system:

Operating System: [Windows 10]
ADB Version: [latest]
Nox Player Version: [7.0.5.7]

I have also ensured that the ADB drivers are properly installed and that my system recognizes the Nox Player instances. Other ADB commands seem to be working, but specifically, the "devices" command is not producing any output.

Could you kindly assist me in determining whether this is a known issue or if there might be an error or bug in my ADB installation? Are there any additional steps I can take to diagnose and resolve the problem?

Thank you in advance for your help and support.

Best regards,
[Slappy]

**Comment by wherewhere** [comment]
But to get device list in this project is use
```cs
var list = new AdbClient().GetDevices();
```

**Comment by yungd1plomat** [comment]
Connect to the Nox player:
```
var client = new AdbClient();
client.Connect("127.0.0.1:62001");
```

Then you can get devices with:
`client.GetDevices();`

For Nox each port starts with 620, for example:
```
127.0.0.1:62001
127.0.0.1:62025
127.0.0.1:62040
```

You can find all nox instance ports with netstat, more details [here](https://habr.com/ru/articles/581252/)
