### ISSUE TITLE
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in AdvancedSharpAdbClient.dll

### ISSUE THREAD

**Issue by mrjay59** [yungd1plomat/AdvancedSharpAdbClient#79]
### What can we do for you?

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in AdvancedSharpAdbClient.dll

Additional information: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

![image](https://github.com/yungd1plomat/AdvancedSharpAdbClient/assets/66785677/f0805ddd-a9a5-4b97-9473-cc5445892225)

use platform
.NET Framework 4.5.2

**Comment by wherewhere** [comment]
Install this nuget https://www.nuget.org/packages/System.Runtime.InteropServices.RuntimeInformation/

**Comment by mrjay59** [comment]
thank u sir

**Comment by wherewhere** [comment]
No need `System.Runtime.InteropServices.RuntimeInformation` on [v2.5.8](https://github.com/yungd1plomat/AdvancedSharpAdbClient/releases/tag/v2.5.8)
