### ISSUE TITLE
SendText works wierdly on special characters

### ISSUE THREAD

**Issue by graysuit** [yungd1plomat/AdvancedSharpAdbClient#82]
### Describe the bug

Is that expected we need to escape special characters ? or may be better library should do itself to be safer, right ?

### Steps to reproduce the bug
```vbnet
Sub Main()
    Dim client = New AdbClient()
    client.Connect("emulator-5554")
    Dim device = client.GetDevices().FirstOrDefault()
    Console.WriteLine(device.Model)

    PassElement.ClearInput()
    PassElement.SendText("#")     'Result = AdvancedSharpAdbClient.Exceptions.InvalidTextException: Text contains invalid symbols
    PassElement.SendText("\#")    'Result = #
    PassElement.SendText("$")     'Result = $
    PassElement.SendText("a$a")   'Result = a
    PassElement.SendText("a\$a")  'Result = a$a
End Sub
```

### NuGet package version

Latest Source

### .NET Platform

.NET Framework 4.6.x

### Platform type

Windows

### System version

windows 10

### IDE

Visual Studio 2017

**Comment by wherewhere** [comment]
Because it is send command to Android Shell. So these spaical characters should add `\` to escape...

**Comment by scottfly189** [comment]
@graysuit Thank you for your solution.
