### ISSUE TITLE
Just Need help.

### ISSUE THREAD

**Issue by glconsultingservice** [yungd1plomat/AdvancedSharpAdbClient#9]
I am just learning how to use this, I am trying to figure out how to zoom in and out using this.  Basically multi touch operation.

Also, if there is a place where I can review multiple examples of AdvanceSharpAdbClient, I would love to review them so I can learn all the different actions I can take.   

My project revolves around automation of form entries within Apps.  I have to be able to scroll and zoom in and out, and type text.

**Comment by yungd1plomat** [comment]
I think you can try KEYCODE_ZOOM_IN and KEYCODE_ZOOM_OUT event, or try to swipe with coordinates
